// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroVox.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeuroVox.Persistence.Migrations
{
    [DbContext(typeof(NeuroVoxDbContext))]
    [Migration("20261002053342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("neurovox")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeuroVox.Domain.Entities.AceAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date");

                    b.Property<string>("AssessmentVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AttentionScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Evaluator")
                        .HasColumnType("text");

                    b.Property<int?>("FluencyScore")
                        .HasColumnType("integer");

                    b.Property<int?>("LanguageScore")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryScore")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("QualityStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VisuospatialScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "VisitId");

                    b.ToTable("AceAssessments", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.ClinicalOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date");

                    b.Property<string>("Evaluator")
                        .HasColumnType("text");

                    b.Property<bool>("IsIndependentlyDocumented")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OutcomeType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ClinicalOutcomes", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.FeatureDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Citation")
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FlaggedForResearchTeamApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("Formula")
                        .HasColumnType("text");

                    b.Property<string>("Implementation")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Layer")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("MorphologicalAnalyzer")
                        .HasColumnType("text");

                    b.Property<string>("NlpDependency")
                        .HasColumnType("text");

                    b.Property<string>("Parser")
                        .HasColumnType("text");

                    b.Property<string>("PosTagger")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Tokenizer")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeatureName", "AlgorithmVersion")
                        .IsUnique();

                    b.ToTable("FeatureDefinitions", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.FeatureMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionVersion")
                        .HasColumnType("text");

                    b.Property<Guid>("FeatureDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCandidateAnnotation")
                        .HasColumnType("boolean");

                    b.Property<int>("Layer")
                        .HasColumnType("integer");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("text");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoftwareVersion")
                        .HasColumnType("text");

                    b.Property<string>("TextValue")
                        .HasColumnType("text");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId", "FeatureName");

                    b.ToTable("FeatureMeasurements", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ParticipantCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "ParticipantCode")
                        .IsUnique();

                    b.ToTable("Participants", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.ResearchProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodingManualVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultReferenceStandard")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InformationUnitSchemaVersion")
                        .HasColumnType("text");

                    b.Property<bool>("IsBlindedAnnotationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetRecordingSecondsMax")
                        .HasColumnType("integer");

                    b.Property<int>("TargetRecordingSecondsMin")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResearchProtocols", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.SpeechRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("text");

                    b.Property<int>("AudioQuality")
                        .HasColumnType("integer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstructionVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MicrophoneDevice")
                        .HasColumnType("text");

                    b.Property<double>("RecordingDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("RecordingEnvironment")
                        .HasColumnType("text");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SpeechDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StimulusId")
                        .HasColumnType("uuid");

                    b.Property<string>("StimulusVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranscriberVersion")
                        .HasColumnType("text");

                    b.Property<string>("TranscriptSource")
                        .HasColumnType("text");

                    b.Property<string>("TranscriptText")
                        .HasColumnType("text");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("SpeechRecordings", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.Stimulus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetPath")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StimulusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stimuli", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.StudyVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("VisitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "VisitType");

                    b.ToTable("StudyVisits", "neurovox");
                });

            modelBuilder.Entity("NeuroVox.Domain.Entities.TherapistAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnnotationVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AnnotatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<double>("EndSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("RaterIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RowCreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RowIsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("RowIsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RowUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SegmentText")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SubmittedBlind")
                        .HasColumnType("boolean");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId", "AnnotatorId");

                    b.ToTable("TherapistAnnotations", "neurovox");
                });
#pragma warning restore 612, 618
        }
    }
}
