# Generated by the NeuroVox API and pushed to this Kaggle account. Do not edit; do not share (it holds one-time tokens).
import base64, json, os, re, subprocess, sys, threading, time, urllib.request, zlib

SRC = json.loads("__SRC__")
API_URL = "__API_URL__"
CUSTOMER_ID = "__CUSTOMER_ID__"
REGISTER_TOKEN = "__REGISTER_TOKEN__"
IDLE_EXIT_MINUTES = __IDLE_MINUTES__
MAX_HOURS = 8.8   # below Kaggle's 9h limit; the API's keeper starts a replacement (on another account from ~7.9h) when this one ends
DRAIN_HOURS = 8   # past this the kernel exits as soon as it is idle, so a restart does not cut a running job

W = "/kaggle/working/ai"
os.makedirs(W, exist_ok=True)
for name, blob in SRC.items():
    with open(os.path.join(W, name), "wb") as f:
        f.write(zlib.decompress(base64.b64decode(blob)))

try:  # Kaggle only enables internet for phone-verified accounts; say so plainly instead of a pip stack trace
    urllib.request.urlopen("https://pypi.org/simple/pip/", timeout=15).read(10)
except Exception:
    sys.exit("KAGGLE_INTERNET_OFF: kernel has no internet access (verify the phone number of this Kaggle account)")

subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "faster-whisper==1.1.0", "zeyrek==0.1.3",
                       "python-multipart==0.0.20", "uvicorn", "fastapi", "joblib"])
subprocess.call([sys.executable, "-m", "pip", "install", "-q", "-U", "transformers", "accelerate"])   # LLM grammar/semantic review (GPU only)
for vad in ("webrtcvad-wheels", "webrtcvad"):   # optional: app.py falls back to no pause detection without it
    if subprocess.call([sys.executable, "-m", "pip", "install", "-q", vad]) == 0:
        break

try:  # GPU accounts run on CUDA, CPU-only sessions (GPU quota used up) fall back to int8 CPU
    HAS_GPU = subprocess.run(["nvidia-smi", "-L"], capture_output=True, timeout=20).returncode == 0
except Exception:
    HAS_GPU = False

env = dict(os.environ, NEUROVOX_AI_API_KEY="__AI_KEY__", NEUROVOX_DEVICE="cuda" if HAS_GPU else "cpu",
           NEUROVOX_STT_MODEL="small", HF_HOME="/kaggle/working/hf")
srv = subprocess.Popen([sys.executable, "-m", "uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8000"], cwd=W, env=env)

cf = "/kaggle/working/cloudflared"
urllib.request.urlretrieve("https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64", cf)
os.chmod(cf, 0o755)
tun = subprocess.Popen([cf, "tunnel", "--no-autoupdate", "--url", "http://127.0.0.1:8000"],
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
url = None
for line in tun.stdout:
    m = re.search(r"https://[a-z0-9-]+\.trycloudflare\.com", line)
    if m:
        url = m.group(0)
        break
threading.Thread(target=lambda: [None for _ in tun.stdout], daemon=True).start()  # keep the pipe drained
print("tunnel ready", flush=True)


def register():
    req = urllib.request.Request(API_URL + "/api/AiHosts/register", data=json.dumps({"url": url, "gpu": HAS_GPU, "version": "__VERSION__"}).encode(), method="POST",
                                 headers={"Content-Type": "application/json", "X-Register-Token": REGISTER_TOKEN, "customerid": CUSTOMER_ID})
    try:
        urllib.request.urlopen(req, timeout=20).read()
        return True
    except urllib.error.HTTPError as e:
        return e.code not in (401, 403, 404, 410)  # token revoked / account deleted -> stop
    except Exception:
        return True  # transient network problem


def idle_seconds():
    try:
        return json.load(urllib.request.urlopen("http://127.0.0.1:8000/health", timeout=5))["idle_seconds"]
    except Exception:
        return 0


started = time.time()
while url and srv.poll() is None:
    age = time.time() - started
    if (not register() or (IDLE_EXIT_MINUTES > 0 and idle_seconds() > IDLE_EXIT_MINUTES * 60) or age > MAX_HOURS * 3600
            or (age > DRAIN_HOURS * 3600 and idle_seconds() > 90)):
        break
    time.sleep(60)
tun.terminate()
srv.terminate()
